# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-15 23:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='signin_name',
            new_name='signing_name',
        ),
    ]
